//! Spectral voice prototype: one canonical address for every editable harmonic.
use super::ParamDef;
use crate::devices::ParamLabel;
use crate::pages::{KeyTable, MachineKey, SubPage};
pub const HARMONICS: usize = 128;
pub const LOG: &[u32] = &[
    ATTACK,
    DECAY,
    RELEASE,
    ORNAMENT_TIME,
    ORNAMENT_SPEED,
    PITCH_TIME,
    PITCH_SPEED,
    VIBRATO_SPEED,
];
pub fn norm(id: u32, value: f32) -> f32 {
    let Some(p) = TABLE.get(id as usize) else {
        return 0.0;
    };
    let value = if value.is_finite() {
        value.clamp(p.min, p.max)
    } else {
        p.default
    };
    if LOG.contains(&id) {
        (value / p.min).ln() / (p.max / p.min).ln()
    } else {
        (value - p.min) / (p.max - p.min)
    }
}
pub fn value(id: u32, norm: f32) -> f32 {
    let Some(p) = TABLE.get(id as usize) else {
        return 0.0;
    };
    let norm = if norm.is_finite() {
        norm.clamp(0.0, 1.0)
    } else {
        return p.default;
    };
    let v = if LOG.contains(&id) {
        p.min * (p.max / p.min).powf(norm)
    } else {
        p.min + norm * (p.max - p.min)
    };
    if discrete(id) { v.round() } else { v }
}
pub fn discrete(id: u32) -> bool {
    matches!(id, ORNAMENT | PITCH_ORNAMENT | MONO)
}
pub const HARMONIC_BASE: u32 = 13;
// Append only: all existing harmonic addresses remain wire-compatible.
pub const EXTRA_BASE: u32 = HARMONIC_BASE + HARMONICS as u32 * 2;
pub const EXTRA_COUNT: usize = 18;
pub const COUNT: usize = EXTRA_BASE as usize + EXTRA_COUNT;
pub const MONO: u32 = EXTRA_BASE + 0;
pub const GLIDE: u32 = EXTRA_BASE + 1;
pub const NOISE: u32 = EXTRA_BASE + 2;
pub const PITCH_ORNAMENT: u32 = EXTRA_BASE + 3;
pub const PITCH_TIME: u32 = EXTRA_BASE + 4;
pub const PITCH_SPEED: u32 = EXTRA_BASE + 5;
pub const PITCH_FROM: u32 = EXTRA_BASE + 6;
pub const PITCH_OTHER: u32 = EXTRA_BASE + 7;
pub const VIBRATO_SPEED: u32 = EXTRA_BASE + 8;
pub const VIBRATO_DEPTH: u32 = EXTRA_BASE + 9;
pub const MACRO_1: u32 = EXTRA_BASE + 10;
pub const MACRO_2: u32 = EXTRA_BASE + 11;
pub const MACRO_3: u32 = EXTRA_BASE + 12;
pub const MACRO_4: u32 = EXTRA_BASE + 13;
pub const MACRO_5: u32 = EXTRA_BASE + 14;
pub const MACRO_6: u32 = EXTRA_BASE + 15;
pub const MACRO_7: u32 = EXTRA_BASE + 16;
pub const MACRO_8: u32 = EXTRA_BASE + 17;
pub const ATTACK: u32 = 0;
pub const DECAY: u32 = 1;
pub const SUSTAIN: u32 = 2;
pub const RELEASE: u32 = 3;
pub const LEVEL: u32 = 4;
pub const MORPH: u32 = 5;
pub const TUNE: u32 = 6;
pub const ORNAMENT: u32 = 7;
pub const ORNAMENT_TIME: u32 = 8;
pub const ORNAMENT_SPEED: u32 = 9;
pub const ORNAMENT_FROM: u32 = 10;
pub const ORNAMENT_OTHER: u32 = 11;
pub const SHIFT: u32 = 12;
pub const ORNAMENT_NAMES: &[&str] = &[
    "off", "kan-swar", "meend", "gamak", "khatka", "andolan", "murki",
];
pub const fn amp(h: usize) -> u32 {
    HARMONIC_BASE + h as u32 * 2
}
pub const fn phase(h: usize) -> u32 {
    amp(h) + 1
}
pub fn harmonic(id: u32) -> Option<(usize, bool)> {
    let n = id.checked_sub(HARMONIC_BASE)? as usize;
    (n < HARMONICS * 2).then_some((n / 2, n % 2 == 1))
}
pub const TABLE: &[ParamDef] = &[
    ParamDef {
        id: ATTACK,
        name: "attack",
        min: 1.0,
        max: 8000.0,
        default: 40.0,
    },
    ParamDef {
        id: DECAY,
        name: "decay",
        min: 5.0,
        max: 12000.0,
        default: 1200.0,
    },
    ParamDef {
        id: SUSTAIN,
        name: "sustain",
        min: 0.0,
        max: 1.0,
        default: 0.7,
    },
    ParamDef {
        id: RELEASE,
        name: "release",
        min: 1.0,
        max: 12000.0,
        default: 1400.0,
    },
    ParamDef {
        id: LEVEL,
        name: "level",
        min: 0.0,
        max: 2.0,
        default: 0.35,
    },
    ParamDef {
        id: MORPH,
        name: "morph",
        min: 0.0,
        max: 4000.0,
        default: 80.0,
    },
    ParamDef {
        id: TUNE,
        name: "tune",
        min: -48.0,
        max: 48.0,
        default: 0.0,
    },
    ParamDef {
        id: ORNAMENT,
        name: "ornament",
        min: 0.0,
        max: 6.0,
        default: 0.0,
    },
    ParamDef {
        id: ORNAMENT_TIME,
        name: "ornament time",
        min: 20.0,
        max: 2000.0,
        default: 400.0,
    },
    ParamDef {
        id: ORNAMENT_SPEED,
        name: "ornament speed",
        min: 0.1,
        max: 16.0,
        default: 2.0,
    },
    ParamDef {
        id: ORNAMENT_FROM,
        name: "ornament from",
        min: -12.0,
        max: 12.0,
        default: 2.0,
    },
    ParamDef {
        id: ORNAMENT_OTHER,
        name: "ornament other",
        min: -12.0,
        max: 12.0,
        default: -1.0,
    },
    ParamDef {
        id: SHIFT,
        name: "shift",
        min: -32.0,
        max: 32.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(0),
        name: "h001_amp",
        min: 0.0,
        max: 1.0,
        default: 0.7,
    },
    ParamDef {
        id: phase(0),
        name: "h001_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(1),
        name: "h002_amp",
        min: 0.0,
        max: 1.0,
        default: 0.35,
    },
    ParamDef {
        id: phase(1),
        name: "h002_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(2),
        name: "h003_amp",
        min: 0.0,
        max: 1.0,
        default: 0.2333333333333333,
    },
    ParamDef {
        id: phase(2),
        name: "h003_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(3),
        name: "h004_amp",
        min: 0.0,
        max: 1.0,
        default: 0.175,
    },
    ParamDef {
        id: phase(3),
        name: "h004_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(4),
        name: "h005_amp",
        min: 0.0,
        max: 1.0,
        default: 0.13999999999999999,
    },
    ParamDef {
        id: phase(4),
        name: "h005_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(5),
        name: "h006_amp",
        min: 0.0,
        max: 1.0,
        default: 0.11666666666666665,
    },
    ParamDef {
        id: phase(5),
        name: "h006_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(6),
        name: "h007_amp",
        min: 0.0,
        max: 1.0,
        default: 0.09999999999999999,
    },
    ParamDef {
        id: phase(6),
        name: "h007_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(7),
        name: "h008_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0875,
    },
    ParamDef {
        id: phase(7),
        name: "h008_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(8),
        name: "h009_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(8),
        name: "h009_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(9),
        name: "h010_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(9),
        name: "h010_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(10),
        name: "h011_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(10),
        name: "h011_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(11),
        name: "h012_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(11),
        name: "h012_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(12),
        name: "h013_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(12),
        name: "h013_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(13),
        name: "h014_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(13),
        name: "h014_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(14),
        name: "h015_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(14),
        name: "h015_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(15),
        name: "h016_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(15),
        name: "h016_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(16),
        name: "h017_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(16),
        name: "h017_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(17),
        name: "h018_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(17),
        name: "h018_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(18),
        name: "h019_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(18),
        name: "h019_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(19),
        name: "h020_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(19),
        name: "h020_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(20),
        name: "h021_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(20),
        name: "h021_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(21),
        name: "h022_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(21),
        name: "h022_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(22),
        name: "h023_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(22),
        name: "h023_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(23),
        name: "h024_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(23),
        name: "h024_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(24),
        name: "h025_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(24),
        name: "h025_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(25),
        name: "h026_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(25),
        name: "h026_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(26),
        name: "h027_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(26),
        name: "h027_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(27),
        name: "h028_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(27),
        name: "h028_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(28),
        name: "h029_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(28),
        name: "h029_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(29),
        name: "h030_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(29),
        name: "h030_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(30),
        name: "h031_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(30),
        name: "h031_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(31),
        name: "h032_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(31),
        name: "h032_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(32),
        name: "h033_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(32),
        name: "h033_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(33),
        name: "h034_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(33),
        name: "h034_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(34),
        name: "h035_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(34),
        name: "h035_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(35),
        name: "h036_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(35),
        name: "h036_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(36),
        name: "h037_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(36),
        name: "h037_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(37),
        name: "h038_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(37),
        name: "h038_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(38),
        name: "h039_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(38),
        name: "h039_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(39),
        name: "h040_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(39),
        name: "h040_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(40),
        name: "h041_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(40),
        name: "h041_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(41),
        name: "h042_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(41),
        name: "h042_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(42),
        name: "h043_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(42),
        name: "h043_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(43),
        name: "h044_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(43),
        name: "h044_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(44),
        name: "h045_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(44),
        name: "h045_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(45),
        name: "h046_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(45),
        name: "h046_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(46),
        name: "h047_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(46),
        name: "h047_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(47),
        name: "h048_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(47),
        name: "h048_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(48),
        name: "h049_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(48),
        name: "h049_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(49),
        name: "h050_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(49),
        name: "h050_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(50),
        name: "h051_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(50),
        name: "h051_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(51),
        name: "h052_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(51),
        name: "h052_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(52),
        name: "h053_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(52),
        name: "h053_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(53),
        name: "h054_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(53),
        name: "h054_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(54),
        name: "h055_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(54),
        name: "h055_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(55),
        name: "h056_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(55),
        name: "h056_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(56),
        name: "h057_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(56),
        name: "h057_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(57),
        name: "h058_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(57),
        name: "h058_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(58),
        name: "h059_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(58),
        name: "h059_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(59),
        name: "h060_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(59),
        name: "h060_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(60),
        name: "h061_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(60),
        name: "h061_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(61),
        name: "h062_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(61),
        name: "h062_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(62),
        name: "h063_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(62),
        name: "h063_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(63),
        name: "h064_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(63),
        name: "h064_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(64),
        name: "h065_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(64),
        name: "h065_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(65),
        name: "h066_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(65),
        name: "h066_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(66),
        name: "h067_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(66),
        name: "h067_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(67),
        name: "h068_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(67),
        name: "h068_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(68),
        name: "h069_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(68),
        name: "h069_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(69),
        name: "h070_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(69),
        name: "h070_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(70),
        name: "h071_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(70),
        name: "h071_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(71),
        name: "h072_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(71),
        name: "h072_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(72),
        name: "h073_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(72),
        name: "h073_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(73),
        name: "h074_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(73),
        name: "h074_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(74),
        name: "h075_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(74),
        name: "h075_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(75),
        name: "h076_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(75),
        name: "h076_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(76),
        name: "h077_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(76),
        name: "h077_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(77),
        name: "h078_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(77),
        name: "h078_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(78),
        name: "h079_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(78),
        name: "h079_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(79),
        name: "h080_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(79),
        name: "h080_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(80),
        name: "h081_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(80),
        name: "h081_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(81),
        name: "h082_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(81),
        name: "h082_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(82),
        name: "h083_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(82),
        name: "h083_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(83),
        name: "h084_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(83),
        name: "h084_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(84),
        name: "h085_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(84),
        name: "h085_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(85),
        name: "h086_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(85),
        name: "h086_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(86),
        name: "h087_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(86),
        name: "h087_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(87),
        name: "h088_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(87),
        name: "h088_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(88),
        name: "h089_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(88),
        name: "h089_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(89),
        name: "h090_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(89),
        name: "h090_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(90),
        name: "h091_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(90),
        name: "h091_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(91),
        name: "h092_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(91),
        name: "h092_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(92),
        name: "h093_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(92),
        name: "h093_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(93),
        name: "h094_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(93),
        name: "h094_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(94),
        name: "h095_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(94),
        name: "h095_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(95),
        name: "h096_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(95),
        name: "h096_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(96),
        name: "h097_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(96),
        name: "h097_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(97),
        name: "h098_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(97),
        name: "h098_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(98),
        name: "h099_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(98),
        name: "h099_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(99),
        name: "h100_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(99),
        name: "h100_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(100),
        name: "h101_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(100),
        name: "h101_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(101),
        name: "h102_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(101),
        name: "h102_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(102),
        name: "h103_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(102),
        name: "h103_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(103),
        name: "h104_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(103),
        name: "h104_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(104),
        name: "h105_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(104),
        name: "h105_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(105),
        name: "h106_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(105),
        name: "h106_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(106),
        name: "h107_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(106),
        name: "h107_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(107),
        name: "h108_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(107),
        name: "h108_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(108),
        name: "h109_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(108),
        name: "h109_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(109),
        name: "h110_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(109),
        name: "h110_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(110),
        name: "h111_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(110),
        name: "h111_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(111),
        name: "h112_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(111),
        name: "h112_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(112),
        name: "h113_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(112),
        name: "h113_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(113),
        name: "h114_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(113),
        name: "h114_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(114),
        name: "h115_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(114),
        name: "h115_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(115),
        name: "h116_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(115),
        name: "h116_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(116),
        name: "h117_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(116),
        name: "h117_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(117),
        name: "h118_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(117),
        name: "h118_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(118),
        name: "h119_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(118),
        name: "h119_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(119),
        name: "h120_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(119),
        name: "h120_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(120),
        name: "h121_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(120),
        name: "h121_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(121),
        name: "h122_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(121),
        name: "h122_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(122),
        name: "h123_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(122),
        name: "h123_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(123),
        name: "h124_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(123),
        name: "h124_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(124),
        name: "h125_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(124),
        name: "h125_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(125),
        name: "h126_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(125),
        name: "h126_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(126),
        name: "h127_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(126),
        name: "h127_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: amp(127),
        name: "h128_amp",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: phase(127),
        name: "h128_phase",
        min: -180.0,
        max: 180.0,
        default: 0.0,
    },
    ParamDef {
        id: MONO,
        name: "mono",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: GLIDE,
        name: "glide",
        min: 0.0,
        max: 1000.0,
        default: 80.0,
    },
    ParamDef {
        id: NOISE,
        name: "noise",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: PITCH_ORNAMENT,
        name: "pitch ornament",
        min: 0.0,
        max: 6.0,
        default: 0.0,
    },
    ParamDef {
        id: PITCH_TIME,
        name: "pitch time",
        min: 20.0,
        max: 2000.0,
        default: 180.0,
    },
    ParamDef {
        id: PITCH_SPEED,
        name: "pitch speed",
        min: 0.1,
        max: 16.0,
        default: 5.0,
    },
    ParamDef {
        id: PITCH_FROM,
        name: "pitch from",
        min: -12.0,
        max: 12.0,
        default: -1.0,
    },
    ParamDef {
        id: PITCH_OTHER,
        name: "pitch other",
        min: -12.0,
        max: 12.0,
        default: 1.0,
    },
    ParamDef {
        id: VIBRATO_SPEED,
        name: "vibrato speed",
        min: 0.1,
        max: 12.0,
        default: 5.2,
    },
    ParamDef {
        id: VIBRATO_DEPTH,
        name: "vibrato depth",
        min: 0.0,
        max: 100.0,
        default: 0.0,
    },
    ParamDef {
        id: MACRO_1,
        name: "macro 1",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: MACRO_2,
        name: "macro 2",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: MACRO_3,
        name: "macro 3",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: MACRO_4,
        name: "macro 4",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: MACRO_5,
        name: "macro 5",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: MACRO_6,
        name: "macro 6",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: MACRO_7,
        name: "macro 7",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
    ParamDef {
        id: MACRO_8,
        name: "macro 8",
        min: 0.0,
        max: 1.0,
        default: 0.0,
    },
];
pub const LABELS: &[ParamLabel] = &[
    ParamLabel {
        name: "attack",
        unit: " ms",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "decay",
        unit: " ms",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "sustain",
        unit: "",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "release",
        unit: " ms",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "level",
        unit: "",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "morph",
        unit: " ms",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "tune",
        unit: " st",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "ornament",
        unit: "",
        group: "Voice",
        choices: ORNAMENT_NAMES,
    },
    ParamLabel {
        name: "ornament time",
        unit: " ms",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "ornament speed",
        unit: " Hz",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "ornament from",
        unit: " bins",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "ornament other",
        unit: " bins",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "shift",
        unit: " bins",
        group: "Voice",
        choices: &[],
    },
    ParamLabel {
        name: "h001_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h001_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h002_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h002_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h003_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h003_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h004_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h004_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h005_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h005_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h006_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h006_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h007_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h007_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h008_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h008_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h009_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h009_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h010_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h010_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h011_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h011_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h012_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h012_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h013_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h013_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h014_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h014_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h015_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h015_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h016_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h016_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h017_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h017_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h018_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h018_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h019_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h019_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h020_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h020_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h021_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h021_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h022_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h022_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h023_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h023_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h024_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h024_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h025_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h025_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h026_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h026_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h027_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h027_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h028_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h028_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h029_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h029_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h030_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h030_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h031_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h031_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h032_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h032_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h033_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h033_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h034_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h034_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h035_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h035_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h036_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h036_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h037_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h037_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h038_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h038_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h039_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h039_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h040_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h040_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h041_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h041_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h042_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h042_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h043_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h043_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h044_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h044_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h045_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h045_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h046_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h046_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h047_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h047_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h048_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h048_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h049_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h049_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h050_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h050_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h051_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h051_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h052_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h052_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h053_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h053_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h054_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h054_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h055_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h055_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h056_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h056_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h057_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h057_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h058_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h058_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h059_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h059_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h060_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h060_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h061_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h061_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h062_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h062_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h063_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h063_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h064_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h064_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h065_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h065_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h066_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h066_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h067_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h067_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h068_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h068_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h069_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h069_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h070_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h070_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h071_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h071_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h072_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h072_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h073_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h073_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h074_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h074_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h075_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h075_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h076_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h076_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h077_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h077_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h078_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h078_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h079_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h079_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h080_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h080_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h081_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h081_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h082_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h082_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h083_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h083_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h084_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h084_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h085_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h085_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h086_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h086_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h087_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h087_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h088_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h088_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h089_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h089_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h090_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h090_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h091_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h091_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h092_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h092_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h093_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h093_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h094_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h094_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h095_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h095_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h096_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h096_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h097_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h097_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h098_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h098_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h099_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h099_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h100_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h100_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h101_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h101_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h102_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h102_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h103_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h103_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h104_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h104_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h105_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h105_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h106_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h106_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h107_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h107_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h108_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h108_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h109_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h109_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h110_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h110_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h111_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h111_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h112_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h112_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h113_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h113_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h114_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h114_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h115_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h115_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h116_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h116_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h117_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h117_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h118_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h118_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h119_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h119_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h120_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h120_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h121_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h121_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h122_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h122_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h123_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h123_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h124_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h124_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h125_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h125_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h126_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h126_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h127_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h127_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h128_amp",
        unit: "",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "h128_phase",
        unit: " deg",
        group: "Spectrum",
        choices: &[],
    },
    ParamLabel {
        name: "mono",
        unit: "",
        group: "Performance",
        choices: &["poly", "legato"],
    },
    ParamLabel {
        name: "glide",
        unit: " ms",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "noise",
        unit: "",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "pitch ornament",
        unit: "",
        group: "Performance",
        choices: ORNAMENT_NAMES,
    },
    ParamLabel {
        name: "pitch time",
        unit: " ms",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "pitch speed",
        unit: " Hz",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "pitch from",
        unit: " st",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "pitch other",
        unit: " st",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "vibrato speed",
        unit: " Hz",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "vibrato depth",
        unit: " ct",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "macro 1",
        unit: "",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "macro 2",
        unit: "",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "macro 3",
        unit: "",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "macro 4",
        unit: "",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "macro 5",
        unit: "",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "macro 6",
        unit: "",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "macro 7",
        unit: "",
        group: "Performance",
        choices: &[],
    },
    ParamLabel {
        name: "macro 8",
        unit: "",
        group: "Performance",
        choices: &[],
    },
];
pub const SRC_PAGES: &[SubPage] = &[
    SubPage {
        title: "Harmonics 001–004",
        slots: [
            Some(amp(0)),
            Some(phase(0)),
            Some(amp(1)),
            Some(phase(1)),
            Some(amp(2)),
            Some(phase(2)),
            Some(amp(3)),
            Some(phase(3)),
        ],
    },
    SubPage {
        title: "Harmonics 005–008",
        slots: [
            Some(amp(4)),
            Some(phase(4)),
            Some(amp(5)),
            Some(phase(5)),
            Some(amp(6)),
            Some(phase(6)),
            Some(amp(7)),
            Some(phase(7)),
        ],
    },
    SubPage {
        title: "Harmonics 009–012",
        slots: [
            Some(amp(8)),
            Some(phase(8)),
            Some(amp(9)),
            Some(phase(9)),
            Some(amp(10)),
            Some(phase(10)),
            Some(amp(11)),
            Some(phase(11)),
        ],
    },
    SubPage {
        title: "Harmonics 013–016",
        slots: [
            Some(amp(12)),
            Some(phase(12)),
            Some(amp(13)),
            Some(phase(13)),
            Some(amp(14)),
            Some(phase(14)),
            Some(amp(15)),
            Some(phase(15)),
        ],
    },
    SubPage {
        title: "Harmonics 017–020",
        slots: [
            Some(amp(16)),
            Some(phase(16)),
            Some(amp(17)),
            Some(phase(17)),
            Some(amp(18)),
            Some(phase(18)),
            Some(amp(19)),
            Some(phase(19)),
        ],
    },
    SubPage {
        title: "Harmonics 021–024",
        slots: [
            Some(amp(20)),
            Some(phase(20)),
            Some(amp(21)),
            Some(phase(21)),
            Some(amp(22)),
            Some(phase(22)),
            Some(amp(23)),
            Some(phase(23)),
        ],
    },
    SubPage {
        title: "Harmonics 025–028",
        slots: [
            Some(amp(24)),
            Some(phase(24)),
            Some(amp(25)),
            Some(phase(25)),
            Some(amp(26)),
            Some(phase(26)),
            Some(amp(27)),
            Some(phase(27)),
        ],
    },
    SubPage {
        title: "Harmonics 029–032",
        slots: [
            Some(amp(28)),
            Some(phase(28)),
            Some(amp(29)),
            Some(phase(29)),
            Some(amp(30)),
            Some(phase(30)),
            Some(amp(31)),
            Some(phase(31)),
        ],
    },
    SubPage {
        title: "Harmonics 033–036",
        slots: [
            Some(amp(32)),
            Some(phase(32)),
            Some(amp(33)),
            Some(phase(33)),
            Some(amp(34)),
            Some(phase(34)),
            Some(amp(35)),
            Some(phase(35)),
        ],
    },
    SubPage {
        title: "Harmonics 037–040",
        slots: [
            Some(amp(36)),
            Some(phase(36)),
            Some(amp(37)),
            Some(phase(37)),
            Some(amp(38)),
            Some(phase(38)),
            Some(amp(39)),
            Some(phase(39)),
        ],
    },
    SubPage {
        title: "Harmonics 041–044",
        slots: [
            Some(amp(40)),
            Some(phase(40)),
            Some(amp(41)),
            Some(phase(41)),
            Some(amp(42)),
            Some(phase(42)),
            Some(amp(43)),
            Some(phase(43)),
        ],
    },
    SubPage {
        title: "Harmonics 045–048",
        slots: [
            Some(amp(44)),
            Some(phase(44)),
            Some(amp(45)),
            Some(phase(45)),
            Some(amp(46)),
            Some(phase(46)),
            Some(amp(47)),
            Some(phase(47)),
        ],
    },
    SubPage {
        title: "Harmonics 049–052",
        slots: [
            Some(amp(48)),
            Some(phase(48)),
            Some(amp(49)),
            Some(phase(49)),
            Some(amp(50)),
            Some(phase(50)),
            Some(amp(51)),
            Some(phase(51)),
        ],
    },
    SubPage {
        title: "Harmonics 053–056",
        slots: [
            Some(amp(52)),
            Some(phase(52)),
            Some(amp(53)),
            Some(phase(53)),
            Some(amp(54)),
            Some(phase(54)),
            Some(amp(55)),
            Some(phase(55)),
        ],
    },
    SubPage {
        title: "Harmonics 057–060",
        slots: [
            Some(amp(56)),
            Some(phase(56)),
            Some(amp(57)),
            Some(phase(57)),
            Some(amp(58)),
            Some(phase(58)),
            Some(amp(59)),
            Some(phase(59)),
        ],
    },
    SubPage {
        title: "Harmonics 061–064",
        slots: [
            Some(amp(60)),
            Some(phase(60)),
            Some(amp(61)),
            Some(phase(61)),
            Some(amp(62)),
            Some(phase(62)),
            Some(amp(63)),
            Some(phase(63)),
        ],
    },
    SubPage {
        title: "Harmonics 065–068",
        slots: [
            Some(amp(64)),
            Some(phase(64)),
            Some(amp(65)),
            Some(phase(65)),
            Some(amp(66)),
            Some(phase(66)),
            Some(amp(67)),
            Some(phase(67)),
        ],
    },
    SubPage {
        title: "Harmonics 069–072",
        slots: [
            Some(amp(68)),
            Some(phase(68)),
            Some(amp(69)),
            Some(phase(69)),
            Some(amp(70)),
            Some(phase(70)),
            Some(amp(71)),
            Some(phase(71)),
        ],
    },
    SubPage {
        title: "Harmonics 073–076",
        slots: [
            Some(amp(72)),
            Some(phase(72)),
            Some(amp(73)),
            Some(phase(73)),
            Some(amp(74)),
            Some(phase(74)),
            Some(amp(75)),
            Some(phase(75)),
        ],
    },
    SubPage {
        title: "Harmonics 077–080",
        slots: [
            Some(amp(76)),
            Some(phase(76)),
            Some(amp(77)),
            Some(phase(77)),
            Some(amp(78)),
            Some(phase(78)),
            Some(amp(79)),
            Some(phase(79)),
        ],
    },
    SubPage {
        title: "Harmonics 081–084",
        slots: [
            Some(amp(80)),
            Some(phase(80)),
            Some(amp(81)),
            Some(phase(81)),
            Some(amp(82)),
            Some(phase(82)),
            Some(amp(83)),
            Some(phase(83)),
        ],
    },
    SubPage {
        title: "Harmonics 085–088",
        slots: [
            Some(amp(84)),
            Some(phase(84)),
            Some(amp(85)),
            Some(phase(85)),
            Some(amp(86)),
            Some(phase(86)),
            Some(amp(87)),
            Some(phase(87)),
        ],
    },
    SubPage {
        title: "Harmonics 089–092",
        slots: [
            Some(amp(88)),
            Some(phase(88)),
            Some(amp(89)),
            Some(phase(89)),
            Some(amp(90)),
            Some(phase(90)),
            Some(amp(91)),
            Some(phase(91)),
        ],
    },
    SubPage {
        title: "Harmonics 093–096",
        slots: [
            Some(amp(92)),
            Some(phase(92)),
            Some(amp(93)),
            Some(phase(93)),
            Some(amp(94)),
            Some(phase(94)),
            Some(amp(95)),
            Some(phase(95)),
        ],
    },
    SubPage {
        title: "Harmonics 097–100",
        slots: [
            Some(amp(96)),
            Some(phase(96)),
            Some(amp(97)),
            Some(phase(97)),
            Some(amp(98)),
            Some(phase(98)),
            Some(amp(99)),
            Some(phase(99)),
        ],
    },
    SubPage {
        title: "Harmonics 101–104",
        slots: [
            Some(amp(100)),
            Some(phase(100)),
            Some(amp(101)),
            Some(phase(101)),
            Some(amp(102)),
            Some(phase(102)),
            Some(amp(103)),
            Some(phase(103)),
        ],
    },
    SubPage {
        title: "Harmonics 105–108",
        slots: [
            Some(amp(104)),
            Some(phase(104)),
            Some(amp(105)),
            Some(phase(105)),
            Some(amp(106)),
            Some(phase(106)),
            Some(amp(107)),
            Some(phase(107)),
        ],
    },
    SubPage {
        title: "Harmonics 109–112",
        slots: [
            Some(amp(108)),
            Some(phase(108)),
            Some(amp(109)),
            Some(phase(109)),
            Some(amp(110)),
            Some(phase(110)),
            Some(amp(111)),
            Some(phase(111)),
        ],
    },
    SubPage {
        title: "Harmonics 113–116",
        slots: [
            Some(amp(112)),
            Some(phase(112)),
            Some(amp(113)),
            Some(phase(113)),
            Some(amp(114)),
            Some(phase(114)),
            Some(amp(115)),
            Some(phase(115)),
        ],
    },
    SubPage {
        title: "Harmonics 117–120",
        slots: [
            Some(amp(116)),
            Some(phase(116)),
            Some(amp(117)),
            Some(phase(117)),
            Some(amp(118)),
            Some(phase(118)),
            Some(amp(119)),
            Some(phase(119)),
        ],
    },
    SubPage {
        title: "Harmonics 121–124",
        slots: [
            Some(amp(120)),
            Some(phase(120)),
            Some(amp(121)),
            Some(phase(121)),
            Some(amp(122)),
            Some(phase(122)),
            Some(amp(123)),
            Some(phase(123)),
        ],
    },
    SubPage {
        title: "Harmonics 125–128",
        slots: [
            Some(amp(124)),
            Some(phase(124)),
            Some(amp(125)),
            Some(phase(125)),
            Some(amp(126)),
            Some(phase(126)),
            Some(amp(127)),
            Some(phase(127)),
        ],
    },
];
pub const KEYS: KeyTable = [
    None,
    Some(MachineKey {
        word: "SRC",
        subpages: SRC_PAGES,
    }),
    Some(MachineKey {
        word: "MOTION",
        subpages: &[SubPage {
            title: "Spectral gestures",
            slots: [
                Some(ORNAMENT),
                Some(ORNAMENT_TIME),
                Some(ORNAMENT_SPEED),
                Some(ORNAMENT_FROM),
                Some(ORNAMENT_OTHER),
                Some(SHIFT),
                Some(MORPH),
                None,
            ],
        }],
    }),
    Some(MachineKey {
        word: "AMP",
        subpages: &[SubPage {
            title: "Voice",
            slots: [
                Some(ATTACK),
                Some(DECAY),
                Some(SUSTAIN),
                Some(RELEASE),
                Some(LEVEL),
                Some(TUNE),
                Some(MONO),
                Some(GLIDE),
            ],
        }],
    }),
    Some(MachineKey {
        word: "PITCH",
        subpages: &[SubPage {
            title: "Shared pitch gestures",
            slots: [
                Some(PITCH_ORNAMENT),
                Some(PITCH_TIME),
                Some(PITCH_SPEED),
                Some(PITCH_FROM),
                Some(PITCH_OTHER),
                Some(VIBRATO_SPEED),
                Some(VIBRATO_DEPTH),
                Some(NOISE),
            ],
        }],
    }),
    Some(MachineKey {
        word: "MACROS",
        subpages: &[SubPage {
            title: "Routable macros",
            slots: [
                Some(MACRO_1),
                Some(MACRO_2),
                Some(MACRO_3),
                Some(MACRO_4),
                Some(MACRO_5),
                Some(MACRO_6),
                Some(MACRO_7),
                Some(MACRO_8),
            ],
        }],
    }),
    None,
    None,
];
